version: 0
metadata:
  name: ''
  description: ''
  owner: '{{ event.head.user.email }}'
  source: '{{ event.head.repo.url }}'
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - release
    payload:
      maxRunTime: 3600
      image: 'node:6'
      command: []
    metadata:
      name: tag
      description: xyz
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
